packages: []

catalogs:
  build:
    "@intlify/unplugin-vue-i18n": ^6.0.8
    "@shikijs/markdown-it": ^3.8.1
    "@vitejs/plugin-vue": ^5.2.4
    beasties: ^0.2.0
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.45.1
    shiki: ^3.8.1
    unplugin: ^2.2.2
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^6.2.3
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.0.0
    vite-plugin-pwa: ^0.21.2
    vite-plugin-vue-devtools: ^7.7.7
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^26.1.1
    vite-ssg-sitemap: ^0.8.1
  dev:
    "@antfu/eslint-config": ^4.11.0
    "@iconify-json/carbon": ^1.2.11
    "@vue-macros/volar": 3.0.0-beta.17
    "@vue/test-utils": ^2.4.6
    cypress: ^14.5.2
    cypress-vite: ^1.6.0
    eslint: ^9.31.0
    eslint-plugin-cypress: ^4.3.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lint-staged: catalog:dev
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.4
    vue-tsc: ^2.2.12
  frontend:
    "@unhead/vue": ^2.0.12
    "@vueuse/core": ^13.5.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.18
    vue-i18n: ^11.1.11
    vue-router: ^4.5.1
  types:
    "@types/markdown-it-link-attributes": ^3.0.5
    "@types/nprogress": ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks

overrides:
  esbuild@<=0.24.2: ">=0.25.0"
  unplugin: catalog:build
  vite: catalog:build
  vite-plugin-inspect: catalog:build
